# TOKEN IDENTIFICACION TELEGRAM
TELEGRAM_TOKEN = "5612970965:AAGdfD8G_BJRFzYDrp6f9n-e7x1g8GunRcQ" # TOKEN EASYBOT 

# APP HEROKU
APP = "easybottelegrram"

# TOKEN DE IDENTIFICACION NGROK
NGROK_TOKEN =  "2GJRWiVLeLWiblrgD6gGdT3iza8_3F2VxbYwh1YK4tLNExmEp" 